insert into users(username,name,password,buisnessUnit) values ('system','admin','$2a$10$9fuJ3S8K1lap4KhkCnKauOgi/elhjtxjDmeC4kqb4nI7PH4bIF/9.','finance');


INSERT INTO fund_requests (business_key, application, comments, transaction_currency, transaction_amount, amount_in_mur, debit_account_number, account_short_name, debit_account_ccy, payment_details_1, payment_details_2, payment_details_3, payment_details_4, verified, discrepancy_reason, created_by, created_on, updated_by, updated_on, customer_number, customer_name, account_officer, alt_account_officer, date_mail_sent, override, bu_name, amount_in_debit_account_ccy, debit_account_balance, beneficiary_account_number, beneficiary_name, beneficiary_bank_name, beneficiary_bank_swift_code, agreed_rate, status)
VALUES ('lease', 'BusinessType', 'NewApplications', 'MUR', '50000', '5000', '982934212', 'ROY', 'MUR', 'online', 'PHONREAPY', 'UPI', 'NETBAKING', 'PENDING', 'WRONG UPI', 'USER', '2023-05-29', 'USER', '2023-05-29', '735487872', 'JOHN', '', '', '2023-05-29', 'Three Days', 'PTL', '90000', '8990', '8226492727', 'Peter', 'ICICI', 'ICICI', '70000', 'UNASSIGNED');

INSERT INTO fund_requests (business_key, application, comments, transaction_currency, transaction_amount, amount_in_mur, debit_account_number, account_short_name, debit_account_ccy, payment_details_1, payment_details_2, payment_details_3, payment_details_4, verified, discrepancy_reason, created_by, created_on, updated_by, updated_on, customer_number, customer_name, account_officer, alt_account_officer, date_mail_sent, override, bu_name, amount_in_debit_account_ccy, debit_account_balance, beneficiary_account_number, beneficiary_name, beneficiary_bank_name, beneficiary_bank_swift_code, agreed_rate, status)
VALUES ('lease', 'BusinessType', 'NewApplications', 'MUR', '10000', '5000', '982934212', 'ROY', 'MUR', 'online', 'PHONREAPY', 'UPI', 'NETBAKING', 'PENDING', 'WRONG UPI', 'USER', '2023-05-29', 'USER', '2023-05-29', '735487872', 'JOHN', '', '', '2023-05-29', 'Three Days', 'PTL', '90000', '8990', '8226492727', 'Peter', 'ICICI', 'ICICI', '70000', 'UNASSIGNED');

INSERT INTO fund_requests (business_key, application, comments, transaction_currency, transaction_amount, amount_in_mur, debit_account_number, account_short_name, debit_account_ccy, payment_details_1, payment_details_2, payment_details_3, payment_details_4, verified, discrepancy_reason, created_by, created_on, updated_by, updated_on, customer_number, customer_name, account_officer, alt_account_officer, date_mail_sent, override, bu_name, amount_in_debit_account_ccy, debit_account_balance, beneficiary_account_number, beneficiary_name, beneficiary_bank_name, beneficiary_bank_swift_code, agreed_rate, status)
VALUES ('lease', 'BusinessType', 'NewApplications', 'MUR', '20000', '5000', '982934212', 'ROY', 'MUR', 'online', 'PHONREAPY', 'UPI', 'NETBAKING', 'PENDING', 'WRONG UPI', 'USER', '2023-05-29', 'USER', '2023-05-29', '735487872', 'JOHN', '', '', '2023-05-29', 'Three Days', 'PTL', '90000', '8990', '8226492727', 'Peter', 'ICICI', 'ICICI', '70000', 'UNASSIGNED');

INSERT INTO fund_requests (business_key, application, comments, transaction_currency, transaction_amount, amount_in_mur, debit_account_number, account_short_name, debit_account_ccy, payment_details_1, payment_details_2, payment_details_3, payment_details_4, verified, discrepancy_reason, created_by, created_on, updated_by, updated_on, customer_number, customer_name, account_officer, alt_account_officer, date_mail_sent, override, bu_name, amount_in_debit_account_ccy, debit_account_balance, beneficiary_account_number, beneficiary_name, beneficiary_bank_name, beneficiary_bank_swift_code, agreed_rate, status)
VALUES ('lease', 'BusinessType', 'NewApplications', 'MUR', '30000', '5000', '982934212', 'ROY', 'MUR', 'online', 'PHONREAPY', 'UPI', 'NETBAKING', 'PENDING', 'WRONG UPI', 'USER', '2023-05-29', 'USER', '2023-05-29', '735487872', 'JOHN', '', '', '2023-05-29', 'Three Days', 'PTL', '90000', '8990', '8226492727', 'Peter', 'ICICI', 'ICICI', '70000', 'UNASSIGNED');

INSERT INTO fund_requests (business_key, application, comments, transaction_currency, transaction_amount, amount_in_mur, debit_account_number, account_short_name, debit_account_ccy, payment_details_1, payment_details_2, payment_details_3, payment_details_4, verified, discrepancy_reason, created_by, created_on, updated_by, updated_on, customer_number, customer_name, account_officer, alt_account_officer, date_mail_sent, override, bu_name, amount_in_debit_account_ccy, debit_account_balance, beneficiary_account_number, beneficiary_name, beneficiary_bank_name, beneficiary_bank_swift_code, agreed_rate, status)
VALUES ('lease', 'BusinessType', 'NewApplications', 'MUR', '80000', '5000', '982934212', 'ROY', 'MUR', 'online', 'PHONREAPY', 'UPI', 'NETBAKING', 'PENDING', 'WRONG UPI', 'USER', '2023-05-29', 'USER', '2023-05-29', '735487872', 'JOHN', '', '', '2023-05-29', 'Three Days', 'PTL', '90000', '8990', '8226492727', 'Peter', 'ICICI', 'ICICI', '70000', 'UNASSIGNED');